modLoader="javafml"
loaderVersion="[31,)"
license="MIT License"

[[mods]]
modId="trumpetskeleton"
version="${file.jarVersion}"
displayName="Trumpet Skeleton"

authors="JamiesWhiteShirt (port by gdude2002) (Updated by MagusEli)"

description='''
The sound of trumpets echoes through the night...
'''

[[dependencies.trumpetskeleton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
